# Site settings
# These are the default settings for a base Jekyll site for GitHub Pages

title: Democropedia
description: In defense of democracy
baseurl: "/democropedia"
url: "https://hofmanniac.github.io" # change this to your GitHub Pages URL

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  principles:
    output: true
    permalink: /principles/:name/

  events:
    output: true
    permalink: /events/:name/

# Exclude these files from production
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
